### ISSUE TITLE
docker部署后登录仍访问教程中地址

### ISSUE THREAD

**Issue by codesensi** [ischenliang/quickly-picture-bed#10]
![image](https://github.com/ischenliang/quickly-picture-bed/assets/66196408/7f422c97-5945-4e45-8fea-0d4a32ad5674)
如图，变量中已正确指定服务端地址
![image](https://github.com/ischenliang/quickly-picture-bed/assets/66196408/c7d65bc1-7f99-457b-bc20-f7f33e56e558)

**Comment by Joackk** [comment]
请问你的docker部署是用项目中的那个docekr，编译后部署的吗？有没有直接拉编译好镜像的docker-compose文件哇_

**Comment by codesensi** [comment]
> 请问你的docker部署是用项目中的那个docekr，编译后部署的吗？有没有直接拉编译好镜像的docker-compose文件哇_

我是直接拉的dockerhub上打包好的镜像部署的

**Comment by Joackk** [comment]
> > 请问你的docker部署是用项目中的那个docekr，编译后部署的吗？有没有直接拉编译好镜像的docker-compose文件哇_
> 
> 我是直接拉的dockerhub上打包好的镜像部署的

拉取那个镜像我一直被提示账号不存在，你有遇到吗？我看服务端和客户端启动都没有报错，但是就是找不到帐号，数据库中也导入了帐号了

**Comment by love2wind** [comment]
我进入client容器，把global.config.js里的window.uploader_ip = 'localhost:3002'这个改了以后就正常了。
