### ISSUE TITLE
启动好了，F12有返回，但是页面没显示

### ISSUE THREAD

**Issue by myding1** [ischenliang/quickly-picture-bed#11]
![image](https://github.com/ischenliang/quickly-picture-bed/assets/65712678/d1bdca02-af4e-44f4-a585-d9412e2022a3)
![image](https://github.com/ischenliang/quickly-picture-bed/assets/65712678/3adf61a6-aed1-474c-b493-ad60451c4abd)

**Comment by ischenliang** [comment]
![image](https://github.com/ischenliang/quickly-picture-bed/assets/115447272/9d9d9e96-e44b-4d6a-919e-dcc57440db23)
把上面的`控制台`和`标头`两处分别截图给我看下，首先看看你连的是是不是本地后端接口，然后我看控制台有一个报错，你截图看看究竟是什么错

**Comment by myding1** [comment]
![image](https://github.com/ischenliang/quickly-picture-bed/assets/65712678/c0ba41d6-a638-4a75-9176-ea0987fcec02)
![image](https://github.com/ischenliang/quickly-picture-bed/assets/65712678/92038d40-8141-4040-a5aa-1dadd98522f8)
![image](https://github.com/ischenliang/quickly-picture-bed/assets/65712678/f036ea17-f49a-4781-bf42-03e98938318f)
![image](https://github.com/ischenliang/quickly-picture-bed/assets/65712678/eee8c31c-59e6-4afd-880a-bdd56fd8ce59)

我配置的端口6001
