### ISSUE TITLE
docker 部署后出现的一个问题

### ISSUE THREAD

**Issue by wleelw** [ischenliang/quickly-picture-bed#12]
![image](https://github.com/ischenliang/quickly-picture-bed/assets/74389842/d19993a3-1bfd-4734-824f-28f57fd881dc)
只要我一访问桶页面，就会立马爆这个错误

**Comment by wleelw** [comment]
又发现一个问题
![image](https://github.com/ischenliang/quickly-picture-bed/assets/74389842/f8f5f543-d6fb-43f3-8d7e-fe5055ea0d6a)

**Comment by ischenliang** [comment]
两个问题应该都是同一原因造成的，应该是你创建数据库时没有选择utf8编码
![image](https://github.com/ischenliang/quickly-picture-bed/assets/115447272/16301858-4112-4a5c-986f-875ee415c257)
![image](https://github.com/ischenliang/quickly-picture-bed/assets/115447272/5138e3f6-889c-4989-b50e-cdafb35d0bea)
