### ISSUE TITLE
admin管理员登陆成功后，上传图片报这个错

### ISSUE THREAD

**Issue by wca8** [ischenliang/quickly-picture-bed#13]
![image](https://github.com/ischenliang/quickly-picture-bed/assets/77438963/ab6b3a97-4490-463b-8650-a3141274f34e)
TypeError: Cannot read properties of null (reading 'version')
    at C:\Users\wangchangan\Desktop\quickly-picture-bed-koa-controller\server\src\controllers\BucketController.ts:68:29
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Joackk** [comment]
这是在映射的80登陆吗？我导入了数据库，数据库里也有账号，但是他就说我账号不存在

**Comment by ischenliang** [comment]
> 这是在映射的80登陆吗？我导入了数据库，数据库里也有账号，但是他就说我账号不存在

请确保连接的数据库的地址和端口是否正确，其次就是确保数据库名称是否正确

**Comment by Joackk** [comment]
> > 这是在映射的80登陆吗？我导入了数据库，数据库里也有账号，但是他就说我账号不存在
> 
> 请确保连接的数据库的地址和端口是否正确，其次就是确保数据库名称是否正确

好像是docker版本client那个的问题，他没连我的后端，连到了作者大佬你的后端去了

**Comment by ischenliang** [comment]
> > > 这是在映射的80登陆吗？我导入了数据库，数据库里也有账号，但是他就说我账号不存在
> > 
> > 
> > 请确保连接的数据库的地址和端口是否正确，其次就是确保数据库名称是否正确
> 
> 好像是docker版本client那个的问题，他没连我的后端，连到了作者大佬你的后端去了

是的，那个docker的client是因为打包后就没办法再使用env环境变量了，所以这个远程client不适用，还是采用从零开始安装部署吧
