### ISSUE TITLE
遇到的几个小问题

### ISSUE THREAD

**Issue by Joackk** [ischenliang/quickly-picture-bed#17]
1、global.config.js 这个文件的内容这个控制着后端地址，而且是必须要填写后端服务器的ip才行，如果用127和localhost这种表示本地的，在其他机器访问时候会出现空白，打开网络看了下发现他在其他机器请求了127.0.0.1:3002端口
2、上传图片后看不到图，复制地址，图片地址是127.0.0.1，改成服务端地址后倒是能正常显示，不知道这是哪里导致的
3、还是第一个文件哪里，用docker打包的话，必须在打包前写好global.config.js文件里的后端地址，不然打包成镜像后，就算进入容器内部修改也不会生效
踩了很多坑，最终算是搞起来了，但是还有这些个问题，作者大佬能不能把这几个设置优化一下哇？尤其是第一个，这个昨天刚与到时候发现搭建用的机器访问就正常，其他机器访问全是空白

**Comment by ischenliang** [comment]
第一个问题改成localhost或者127.0.0.1的话，你明白整个原理吗？你改成localhost就相当于是针对本机而言了，其他访问电脑访问那地址是不是也是localhost，此时又是针对你当前使用的机器了，那这个时候你当前访问的机器有部署后端代码吗？



在 2023-07-11 17:33:53，"k sir" ***@***.***> 写道：

1、global.config.js 这个文件的内容这个控制着后端地址，而且是必须要填写后端服务器的ip才行，如果用127和localhost这种表示本地的，在其他机器访问时候会出现空白，打开网络看了下发现他在其他机器请求了127.0.0.1:3002端口
2、上传图片后看不到图，复制地址，图片地址是127.0.0.1，改成服务端地址后倒是能正常显示，不知道这是哪里导致的
3、还是第一个文件哪里，用docker打包的话，必须在打包前写好global.config.js文件里的后端地址，不然打包成镜像后，就算进入容器内部修改也不会生效
踩了很多坑，最终算是搞起来了，但是还有这些个问题，作者大佬能不能把这几个设置优化一下哇？尤其是第一个，这个昨天刚与到时候发现搭建用的机器访问就正常，其他机器访问全是空白

**Comment by ischenliang** [comment]
第二个问题也是同样的原因，你改成127.0.0.1后图片是上传到你此时访问的电脑上，那自然使用127.0.0.1可以正常访问，然后你改成服务端地址的话也就是图片上传到你的服务器上，那自然可以正常访问



在 2023-07-11 17:33:53，"k sir" ***@***.***> 写道：

1、global.config.js 这个文件的内容这个控制着后端地址，而且是必须要填写后端服务器的ip才行，如果用127和localhost这种表示本地的，在其他机器访问时候会出现空白，打开网络看了下发现他在其他机器请求了127.0.0.1:3002端口
2、上传图片后看不到图，复制地址，图片地址是127.0.0.1，改成服务端地址后倒是能正常显示，不知道这是哪里导致的
3、还是第一个文件哪里，用docker打包的话，必须在打包前写好global.config.js文件里的后端地址，不然打包成镜像后，就算进入容器内部修改也不会生效
踩了很多坑，最终算是搞起来了，但是还有这些个问题，作者大佬能不能把这几个设置优化一下哇？尤其是第一个，这个昨天刚与到时候发现搭建用的机器访问就正常，其他机器访问全是空白

**Comment by ischenliang** [comment]
还是麻烦你先搞清楚基本的互联网思维原理



在 2023-07-11 17:33:53，"k sir" ***@***.***> 写道：

1、global.config.js 这个文件的内容这个控制着后端地址，而且是必须要填写后端服务器的ip才行，如果用127和localhost这种表示本地的，在其他机器访问时候会出现空白，打开网络看了下发现他在其他机器请求了127.0.0.1:3002端口
2、上传图片后看不到图，复制地址，图片地址是127.0.0.1，改成服务端地址后倒是能正常显示，不知道这是哪里导致的
3、还是第一个文件哪里，用docker打包的话，必须在打包前写好global.config.js文件里的后端地址，不然打包成镜像后，就算进入容器内部修改也不会生效
踩了很多坑，最终算是搞起来了，但是还有这些个问题，作者大佬能不能把这几个设置优化一下哇？尤其是第一个，这个昨天刚与到时候发现搭建用的机器访问就正常，其他机器访问全是空白

**Comment by ischenliang** [comment]
第三个问题也是，我在安装部署文档里写的明明白白的，docker部署时传入环境变量文件



自己不知道好好看看安装部署文档？










在 2023-07-11 17:33:53，"k sir" ***@***.***> 写道：

1、global.config.js 这个文件的内容这个控制着后端地址，而且是必须要填写后端服务器的ip才行，如果用127和localhost这种表示本地的，在其他机器访问时候会出现空白，打开网络看了下发现他在其他机器请求了127.0.0.1:3002端口
2、上传图片后看不到图，复制地址，图片地址是127.0.0.1，改成服务端地址后倒是能正常显示，不知道这是哪里导致的
3、还是第一个文件哪里，用docker打包的话，必须在打包前写好global.config.js文件里的后端地址，不然打包成镜像后，就算进入容器内部修改也不会生效
踩了很多坑，最终算是搞起来了，但是还有这些个问题，作者大佬能不能把这几个设置优化一下哇？尤其是第一个，这个昨天刚与到时候发现搭建用的机器访问就正常，其他机器访问全是空白

**Comment by ischenliang** [comment]
第三个问题也是，我在安装部署文档里写的明明白白的，docker部署时传入环境变量文件
![image](https://github.com/ischenliang/quickly-picture-bed/assets/115447272/aa897af5-d108-4012-afa0-19a4de428401)


不知道好好看看安装部署文档？

**Comment by Joackk** [comment]
> 第三个问题也是，我在安装部署文档里写的明明白白的，docker部署时传入环境变量文件 ![image](https://user-images.githubusercontent.com/115447272/252825483-aa897af5-d108-4012-afa0-19a4de428401.png)
> 
> 不知道好好看看安装部署文档？

这个我改了，但是没有生效，看链接还是连打包前填写的，环境变量不能正常生效

**Comment by Joackk** [comment]
> 第一个问题改成localhost或者127.0.0.1的话，你明白整个原理吗？你改成localhost就相当于是针对本机而言了，其他访问电脑访问那地址是不是也是localhost，此时又是针对你当前使用的机器了，那这个时候你当前访问的机器有部署后端代码吗？

这个问题就在于如果做成docker镜像，那么他就固定了，我就算进入容器修改，他还是去连做成镜像前的，而且docker环境变量不知为何不会生效，我进入容器修改，重启后连接还是找之前的

**Comment by Joackk** [comment]
> 第二个问题也是同样的原因，你改成127.0.0.1后图片是上传到你此时访问的电脑上，那自然使用127.0.0.1可以正常访问 然后你改成服务端地址的话也就是图片上传到你的服务器上，那自然可以正常访问

我的意思是，我上传了图片后他裂了，直接复制图片地址，得到的却是127.0.0.1，这时候不该得到的是后端的地址+图片路径吗，这个是哪个部分控制的
