### ISSUE TITLE
上传的图片能使用域名访问吗

### ISSUE THREAD

**Issue by biuabiu** [ischenliang/quickly-picture-bed#2]

**Comment by ischenliang** [comment]
目前本地存储桶是还没有做域名支持的，原因是这个系统支持自定义部署，所以需要部署人员自己配置nginx代理，然后只需要将配置的后端接口域名那里改成配好的域名就好了。

然后其他的像`七牛云存储桶`、`阿里云存储桶`、`腾讯云存储桶`等这些对象存储桶都是支持域名访问的，需要自己配置对象存储信息，可以查看到对应的配置文档的(具体查看配置文档步骤如下图所示)。
![202303090838449.png](http://img.itchenliang.club/img/202303090838449.png)

**Comment by ischenliang** [comment]
然后`[picture.itchenliang.club/](http://picture.itchenliang.club/)`这个域名是做开源演示用的，就没有去做过多的nginx代理配置
