### ISSUE TITLE
有关图床的图片分类问题

### ISSUE THREAD

**Issue by qtencent7** [ischenliang/quickly-picture-bed#20]
在实际开发中，比如前端要展示商品图和轮播图这两种，后端怎么样去定义图片的路径呢？方便后端识别，把对应路径里面的图片，返回给对应的前端数据接口里？求解

**Comment by it-chenliang** [comment]
这种的话我了解到的都有几种方式。
对于商品图：
- 一般是直接在创建商品时上传对应的图片，然后数据库里存储图片访问地址  =》 针对于商品的轮播图
- 另一种就是将商品图上传后复制指定的图片链接直接插入到商品描述中 =》针对于商品的描述

对于轮播图的话就有多种方式了：
- 1、创建对应的轮播图管理功能：然后这里面就是管理对应的轮播图了，这种方式一般用于轮播图有交互的形式，比如点击某个轮播图到指定的页面
- 2、直接在图库里把指定的一组图片标记为轮播图
- ....
