### ISSUE TITLE
有没有API

### ISSUE THREAD

**Issue by cs772421** [ischenliang/quickly-picture-bed#22]
建议：
www.a.com代表图床
www.b.com代表博客网站

比如我要把这个www..a.com图床
引入到
B站的www.b.com的文章编辑框里，
有没有一键添加的代码可以导入。
就是说，我不用登录这个图床，就可以在WWW.B.COM里面的文章编辑框直接上传。
而且是支持匿名上传的，我在www.a,com图床里指定一个文件夹，所有的匿名上传的图片都存在这个文件夹里，而文件夹里以年份-月份来分开存图片

**Comment by it-chenliang** [comment]
这个的话目前是不行的，因为我们这个图床系统主要是做的集成第三方对象存储功能为主，除了本地存储桶外，使用其他的对象存储桶上传的文件实际都是保存在第三方对象存储里的，而不是在我们系统中，我们系统里只是基于这个层面做了一层包装，可以上传记录和对图片进行一系列的分组而已，而第三方存储的话则是需要通过签名认证的，如果不需要登录而直接匿名上传的话，就会导致信息泄露等安全问题的
