### ISSUE TITLE
部署方式有点复杂。。

### ISSUE THREAD

**Issue by Mabisi** [ischenliang/quickly-picture-bed#27]
可以打包成DOCKER就好了~

**Comment by it-chenliang** [comment]
我说你是没看到人家写了docker的部署方式的吗，而且文档中写的很明确，由于客户端的原因目前客户端还未找到合理的解决方案的嘛

**Comment by ischenliang** [comment]
> 可以打包成DOCKER就好了~

我现在客户端还没找到合理的配置接口地址的方法，还在尝试新的方法

**Comment by ischenliang** [comment]
或者你有没有好的解决办法，可以给我提供给我参考

**Comment by ischenliang** [comment]
Docker部署方式已上线，可以简化部署方式。

**Comment by ischenliang** [comment]
> > 可以打包成DOCKER就好了~
> 
> 我现在客户端还没找到合理的配置接口地址的方法，还在尝试新的方法

已经找到解决办法了
