### ISSUE TITLE
最新版docker部署后，出现问题

### ISSUE THREAD

**Issue by xiaonian233** [ischenliang/quickly-picture-bed#28]
最新版docker部署后，出现问题。页面空白请求什么的完全正常
没有跳转到login页还是跳转到了undefined页面
无论是自己build镜像还是直接拉取镜像都是一样的。测试本地也会如此
![image](https://github.com/ischenliang/quickly-picture-bed/assets/21072615/d569b7be-c976-49e1-ad89-b208fd961410)
控制台这个错误：、
![image](https://github.com/ischenliang/quickly-picture-bed/assets/21072615/a44e48db-424d-4ff8-85c1-93fe7bbb440f)

**Comment by ischenliang** [comment]
你看下default接口返回的数据是怎样的呢

**Comment by xiaonian233** [comment]
![image](https://github.com/ischenliang/quickly-picture-bed/assets/21072615/2f543b2c-6531-4ac9-b74c-001c0d9a2076)

**Comment by ischenliang** [comment]
你加我个微信吧，我帮你看看具体是啥问题
微信: CL13281289371
