### ISSUE TITLE
运行server报错

### ISSUE THREAD

**Issue by JGPeng** [ischenliang/quickly-picture-bed#3]
![image](https://user-images.githubusercontent.com/54806048/223972838-8548afed-8d97-4f1f-abac-4701bb2d773e.png)

**Comment by love2wind** [comment]
我也是同样的错误

**Comment by ischenliang** [comment]
没遇到过这样的问题，看看是不是数据连接配置那里没有修改

**Comment by JGPeng** [comment]
> 没遇到过这样的问题，看看是不是数据连接配置那里没有修改

这里报错是ts报错，我给params加个强类型声明any就好了，但是网页打开是空白的，不知道是哪里的问题

**Comment by it-chenliang** [comment]
> > 没遇到过这样的问题，看看是不是数据连接配置那里没有修改
> 
> 这里报错是ts报错，我给params加个强类型声明any就好了，但是网页打开是空白的，不知道是哪里的问题

出现白屏或者控制栏输出`website`错误，大概率使用由于前端配置后端接口地址没改，注意配置时是不用加`http`协议的

**Comment by love2wind** [comment]
> > 没遇到过这样的问题，看看是不是数据连接配置那里没有修改
> 
> 这里报错是ts报错，我给params加个强类型声明any就好了，但是网页打开是空白的，不知道是哪里的问题

怎么加，能说下吗

**Comment by ischenliang** [comment]
> > > 没遇到过这样的问题，看看是不是数据连接配置那里没有修改
> > 
> > 
> > 这里报错是ts报错，我给params加个强类型声明any就好了，但是网页打开是空白的，不知道是哪里的问题
> 
> 怎么加，能说下吗

该问题已修复，请重新拉取最新代码
