### ISSUE TITLE
上传的时候能不能按时间生成存储路径

### ISSUE THREAD

**Issue by gradendripar** [ischenliang/quickly-picture-bed#4]
就比如今天上传的图片就存储在2023/03/19文件夹下，文件名为时间戳命名，比如为202303191825459.png
能不能出一个这样的设置，就比较完美了感觉

**Comment by ischenliang** [comment]
> 就比如今天上传的图片就存储在2023/03/19文件夹下，文件名为时间戳命名，比如为202303191825459.png 能不能出一个这样的设置，就比较完美了感觉

已在【本地存储桶】中添加了该功能，需要更新存储桶，操作步骤如下:
1. 更新存储桶
> 由于存储桶更新了版本，以前新建的【本地存储桶】会有一个`new`标签，点击【编辑】按钮更新
![image](https://user-images.githubusercontent.com/115447272/226223983-5ce0583d-0caa-460c-9094-0f023308b52f.png)
2. 在更新存储桶弹窗中，选择自定义路径，对应生成规则如下:
 - 年: year
 - 年月: year/month
 - 年月日: year/month/day
![image](https://user-images.githubusercontent.com/115447272/226224516-3eea74f7-eb7a-468b-85ef-dc93d8ca717c.png)
3. 去上传区选择【本地存储桶】后上传图片
![image](https://user-images.githubusercontent.com/115447272/226225060-e9a014bb-c8f0-4104-9fbf-657bdfee3d29.png)

**Comment by ischenliang** [comment]
> 就比如今天上传的图片就存储在2023/03/19文件夹下，文件名为时间戳命名，比如为202303191825459.png 能不能出一个这样的设置，就比较完美了感觉

可以前往[演示环境](http://picture.itchenliang.club/#/)体验看
