### ISSUE TITLE
部署还是不成功，能不能搞个docker啊

### ISSUE THREAD

**Issue by love2wind** [ischenliang/quickly-picture-bed#6]
拉取最新代码，重新部署，还是启动不起来
![image](https://user-images.githubusercontent.com/11996852/228725349-b4d31b61-4e25-4159-9141-7809fb2c1ae6.png)
![image](https://user-images.githubusercontent.com/11996852/228725493-d2de32ef-3307-4c86-b39c-752049b3e9f7.png)

**Comment by brdctrai** [comment]
有解决方案吗？

**Comment by it-chenliang** [comment]
docker预编译版本在最新版本已添加，请拉取最新版本使用，目前需要自己分别在`client`和`server`下使用`docker build -t xxx .`构建镜像，后续会使用`docker-compose`方式一键构建部署

**Comment by it-chenliang** [comment]
> 拉取最新代码，重新部署，还是启动不起来 ![image](https://user-images.githubusercontent.com/11996852/228725349-b4d31b61-4e25-4159-9141-7809fb2c1ae6.png) ![image](https://user-images.githubusercontent.com/11996852/228725493-d2de32ef-3307-4c86-b39c-752049b3e9f7.png)

该问题在最新版已修复，请下载最新版本使用

**Comment by love2wind** [comment]
> > 拉取最新代码，重新部署，还是启动不起来 ![image](https://user-images.githubusercontent.com/11996852/228725349-b4d31b61-4e25-4159-9141-7809fb2c1ae6.png) ![image](https://user-images.githubusercontent.com/11996852/228725493-d2de32ef-3307-4c86-b39c-752049b3e9f7.png)
> 
> 该问题在最新版已修复，请下载最新版本使用

好的
